title: George (Alex) Adam # your site title
author: GitHub User
description: Machine Learning Blog # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alexadam.ca" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  georgeadam # replace with your_github_username or comment to remove link from footer
social:
  name: George Adam
  links:
    - https://www.linkedin.com/in/alex-adam-23ba02107/
    - https://github.com/georgeadam

disqus:
  shortname: alexadam-ca # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
